// ╔══════════════════════════════════════════════════════════════════════╗
// ║  DICO PERSO 2028 — Vocabulaire personnel consolidé                  ║
// ║  Sources :                                                           ║
// ║    assimil  → Fichier Assimil perso (228 entrées)                   ║
// ║    bouffe   → Vocabulaire gastronomique web (123 entrées)           ║
// ║    michelin → Guide Michelin vocabulaire de base (138 entrées)      ║
// ╚══════════════════════════════════════════════════════════════════════╝
//
// Chaque entrée contient :
//   kana        — hiragana / katakana
//   romaji      — transcription romaji
//   fr          — traduction française
//   kanji       — kanji si disponible (sinon '')
//   theme       — identifiant du thème
//   theme_label — libellé du thème affiché
//   level       — 1 (mot), 2 (phrase courte), 3 (phrase avancée)
//   pack        — toujours 'perso' pour ce dico
//   source      — 'assimil' | 'bouffe' | 'michelin'
//   source_label — nom affiché de la source
//   examples    — tableau d'exemples { jp, romaji, fr }

const DICO_PERSO_2028 = [

  // ══════════════════════════════════════════════════════════════
  //  SOURCE : ASSIMIL — Fichier personnel
  // ══════════════════════════════════════════════════════════════

  // ── VERBES
  {
    kana: 'あります',
    romaji: 'arimasu / aru',
    fr: 'se trouver, exister (objets, choses)',
    kanji: '',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'おかねがあります。', romaji: 'Okane ga arimasu.', fr: 'J\'ai de l\'argent. (litt. de l\'argent existe)' },
      { jp: 'えきはあそこにあります。', romaji: 'Eki wa asoko ni arimasu.', fr: 'La gare est là-bas.' },
    ],
  },
  {
    kana: 'あるきます',
    romaji: 'arukimasu / aruku',
    fr: 'marcher',
    kanji: '歩きます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'えきまであるきます。', romaji: 'Eki made arukimasu.', fr: 'Je marche jusqu\'à la gare.' },
      { jp: 'まいにちさんぽします。', romaji: 'Mainichi sanpo shimasu.', fr: 'Je me promène tous les jours.' },
    ],
  },
  {
    kana: 'できます',
    romaji: 'dekimasu / dekiru',
    fr: 'pouvoir faire, être capable',
    kanji: '',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんごができます。', romaji: 'Nihongo ga dekimasu.', fr: 'Je parle japonais. (litt. je suis capable en japonais)' },
      { jp: 'およぐことができます。', romaji: 'Oyogu koto ga dekimasu.', fr: 'Je sais nager.' },
    ],
  },
  {
    kana: 'です',
    romaji: 'desu',
    fr: 'être, est (copule)',
    kanji: '',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'これはほんです。', romaji: 'Kore wa hon desu.', fr: 'Ceci est un livre.' },
      { jp: 'わたしはフランスじんです。', romaji: 'Watashi wa Furansu-jin desu.', fr: 'Je suis français(e).' },
    ],
  },
  {
    kana: 'はいります',
    romaji: 'hairimasu / hairu',
    fr: 'entrer',
    kanji: '入ります',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'へやにはいります。', romaji: 'Heya ni hairimasu.', fr: 'J\'entre dans la chambre.' },
      { jp: 'おんせんにはいりたいです。', romaji: 'Onsen ni hairitai desu.', fr: 'Je veux entrer dans les sources thermales.' },
    ],
  },
  {
    kana: 'はなします',
    romaji: 'hanashimasu / hanasu',
    fr: 'parler',
    kanji: '話します',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんごをはなします。', romaji: 'Nihongo o hanashimasu.', fr: 'Je parle japonais.' },
      { jp: 'すこしだけはなせます。', romaji: 'Sukoshi dake hanasemasu.', fr: 'Je parle juste un peu.' },
    ],
  },
  {
    kana: 'はたらきます',
    romaji: 'hatarakimasu / hataraku',
    fr: 'travailler',
    kanji: '働きます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どこではたらいていますか？', romaji: 'Doko de hataraite imasu ka?', fr: 'Où travaillez-vous ?' },
    ],
  },
  {
    kana: 'いきます',
    romaji: 'ikimasu / iku',
    fr: 'aller (vers l\'extérieur)',
    kanji: '行きます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんにいきます。', romaji: 'Nihon ni ikimasu.', fr: 'Je vais au Japon.' },
      { jp: 'えきにいきます。', romaji: 'Eki ni ikimasu.', fr: 'Je vais à la gare.' },
    ],
  },
  {
    kana: 'います',
    romaji: 'imasu / iru',
    fr: 'se trouver, exister (êtres vivants)',
    kanji: '',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんじんのともだちがいます。', romaji: 'Nihonjin no tomodachi ga imasu.', fr: 'J\'ai un ami japonais.' },
      { jp: 'だれかいますか？', romaji: 'Dare ka imasu ka?', fr: 'Il y a quelqu\'un ?' },
    ],
  },
  {
    kana: 'かいます',
    romaji: 'kaimasu / kau',
    fr: 'acheter',
    kanji: '買います',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'おみやげをかいます。', romaji: 'Omiyage o kaimasu.', fr: 'J\'achète des souvenirs.' },
      { jp: 'このさけをかいました。', romaji: 'Kono sake o kaimashita.', fr: 'J\'ai acheté ce saké.' },
    ],
  },
  {
    kana: 'きます',
    romaji: 'kimasu / kuru',
    fr: 'venir (vers ici)',
    kanji: '来ます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'フランスからきました。', romaji: 'Furansu kara kimashita.', fr: 'Je viens de France.' },
      { jp: 'またきます！', romaji: 'Mata kimasu!', fr: 'Je reviendrai !' },
    ],
  },
  {
    kana: 'まちます',
    romaji: 'machimasu / matsu',
    fr: 'attendre',
    kanji: '待ちます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ちょっとまってください。', romaji: 'Chotto matte kudasai.', fr: 'Attendez un instant, s\'il vous plaît.' },
      { jp: 'ともだちをまっています。', romaji: 'Tomodachi o matte imasu.', fr: 'J\'attends un ami.' },
    ],
  },
  {
    kana: 'まがります',
    romaji: 'magarimasu / magaru',
    fr: 'tourner',
    kanji: '曲がります',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ひだりにまがってください。', romaji: 'Hidari ni magatte kudasai.', fr: 'Tournez à gauche, s\'il vous plaît.' },
      { jp: 'つぎのかどをみぎにまがります。', romaji: 'Tsugi no kado o migi ni magarimasu.', fr: 'Je tourne à droite au prochain carrefour.' },
    ],
  },
  {
    kana: 'みます',
    romaji: 'mimasu / miru',
    fr: 'regarder, voir',
    kanji: '見ます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ふじさんをみました。', romaji: 'Fujisan o mimashita.', fr: 'J\'ai vu le Mont Fuji.' },
      { jp: 'てれびをみます。', romaji: 'Terebi o mimasu.', fr: 'Je regarde la télé.' },
    ],
  },
  {
    kana: 'みせます',
    romaji: 'misemasu / miseru',
    fr: 'montrer',
    kanji: '見せます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'それをみせてください。', romaji: 'Sore o misete kudasai.', fr: 'Montrez-moi ça, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'みつけます',
    romaji: 'mitsukemasu / mitsukeru',
    fr: 'trouver',
    kanji: '見つけます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いいレストランをみつけました。', romaji: 'Ii resutoran o mitsukemashita.', fr: 'J\'ai trouvé un bon restaurant.' },
    ],
  },
  {
    kana: 'ねます',
    romaji: 'nemasu / neru',
    fr: 'se coucher, dormir',
    kanji: '寝ます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'りょかんでねます。', romaji: 'Ryokan de nemasu.', fr: 'Je dors dans un ryokan.' },
      { jp: 'なんじにねますか？', romaji: 'Nanji ni nemasu ka?', fr: 'À quelle heure vous couchez-vous ?' },
    ],
  },
  {
    kana: 'のみます',
    romaji: 'nomimasu / nomu',
    fr: 'boire',
    kanji: '飲みます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'さけをのみます。', romaji: 'Sake o nomimasu.', fr: 'Je bois du saké.' },
      { jp: 'みずをのんでもいいですか？', romaji: 'Mizu o nonde mo ii desu ka?', fr: 'Puis-je boire de l\'eau ?' },
    ],
  },
  {
    kana: 'おきます',
    romaji: 'okimasu / okiru',
    fr: 'se lever',
    kanji: '起きます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ろくじにおきます。', romaji: 'Roku-ji ni okimasu.', fr: 'Je me lève à 6 heures.' },
    ],
  },
  {
    kana: 'します',
    romaji: 'shimasu / suru',
    fr: 'faire',
    kanji: '',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'かいものをします。', romaji: 'Kaimono o shimasu.', fr: 'Je fais des courses.' },
      { jp: 'さんぽをしましょう！', romaji: 'Sanpo o shimasho!', fr: 'Allons nous promener !' },
    ],
  },
  {
    kana: 'すきです',
    romaji: 'suki desu',
    fr: 'aimer (apprécier)',
    kanji: '好きです',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'さけがすきです。', romaji: 'Sake ga suki desu.', fr: 'J\'aime le saké.' },
      { jp: 'にほんりょうりがだいすきです。', romaji: 'Nihon ryōri ga daisuki desu.', fr: 'J\'adore la cuisine japonaise.' },
    ],
  },
  {
    kana: 'たべます',
    romaji: 'tabemasu / taberu',
    fr: 'manger',
    kanji: '食べます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'すしをたべます。', romaji: 'Sushi o tabemasu.', fr: 'Je mange des sushis.' },
      { jp: 'なにをたべましたか？', romaji: 'Nani o tabemashita ka?', fr: 'Qu\'est-ce que vous avez mangé ?' },
    ],
  },
  {
    kana: 'つきます',
    romaji: 'tsukimasu / tsuku',
    fr: 'arriver (à un endroit)',
    kanji: '着きます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'えきにつきました。', romaji: 'Eki ni tsukimashita.', fr: 'Je suis arrivé(e) à la gare.' },
      { jp: 'なんじにつきますか？', romaji: 'Nanji ni tsukimasu ka?', fr: 'À quelle heure arrive-t-on ?' },
    ],
  },
  {
    kana: 'わかります',
    romaji: 'wakarimasu / wakaru',
    fr: 'comprendre, savoir',
    kanji: '分かります',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'わかりません。', romaji: 'Wakarimasen.', fr: 'Je ne comprends pas.' },
      { jp: 'すこしわかります。', romaji: 'Sukoshi wakarimasu.', fr: 'Je comprends un peu.' },
    ],
  },
  {
    kana: 'わすれます',
    romaji: 'wasuremasu / wasureru',
    fr: 'oublier',
    kanji: '忘れます',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'かぎをわすれました。', romaji: 'Kagi o wasuremashita.', fr: 'J\'ai oublié ma clé.' },
      { jp: 'なまえをわすれてしまいました。', romaji: 'Namae o wasurete shimaimashita.', fr: 'J\'ai oublié le nom.' },
    ],
  },
  {
    kana: 'りょうりします',
    romaji: 'ryōri shimasu',
    fr: 'cuisiner, préparer un repas',
    kanji: '料理します',
    theme: 'verbes',
    theme_label: 'Verbes',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんりょうりをつくります。', romaji: 'Nihon ryōri o tsukurimasu.', fr: 'Je prépare de la cuisine japonaise.' },
    ],
  },

  // ── ADVERBES / MOTS-OUTILS (Assimil)
  {
    kana: 'あした',
    romaji: 'ashita',
    fr: 'demain',
    kanji: '明日',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'あしたにほんにいきます。', romaji: 'Ashita Nihon ni ikimasu.', fr: 'Demain je vais au Japon.' },
    ],
  },
  {
    kana: 'あつい',
    romaji: 'atsui',
    fr: 'chaud (météo ET toucher)',
    kanji: '暑い',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'きょうはとてもあついです。', romaji: 'Kyō wa totemo atsui desu.', fr: 'Il fait très chaud aujourd\'hui.' },
      { jp: 'このスープはあついです。', romaji: 'Kono sūpu wa atsui desu.', fr: 'Cette soupe est chaude.' },
    ],
  },
  {
    kana: 'でも',
    romaji: 'demo',
    fr: 'mais',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'たかいです。でも、かいたいです。', romaji: 'Takai desu. Demo, kaitai desu.', fr: 'C\'est cher. Mais je veux l\'acheter.' },
    ],
  },
  {
    kana: 'どこ',
    romaji: 'doko',
    fr: 'où',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'えきはどこですか？', romaji: 'Eki wa doko desu ka?', fr: 'Où est la gare ?' },
      { jp: 'どこからきましたか？', romaji: 'Doko kara kimashita ka?', fr: 'D\'où venez-vous ?' },
    ],
  },
  {
    kana: 'どうして',
    romaji: 'dōshite',
    fr: 'pourquoi',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どうしてにほんごをべんきょうしていますか？', romaji: 'Dōshite nihongo o benkyō shite imasu ka?', fr: 'Pourquoi étudiez-vous le japonais ?' },
    ],
  },
  {
    kana: 'はやく',
    romaji: 'hayaku',
    fr: 'vite, tôt',
    kanji: '早く',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'はやくきてください。', romaji: 'Hayaku kite kudasai.', fr: 'Venez vite, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'ほんとう',
    romaji: 'hontō',
    fr: 'vrai, vraiment',
    kanji: '本当',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ほんとうにおいしい！', romaji: 'Hontō ni oishii!', fr: 'C\'est vraiment délicieux !' },
      { jp: 'ほんとうですか？', romaji: 'Hontō desu ka?', fr: 'Vraiment ?' },
    ],
  },
  {
    kana: 'いくら',
    romaji: 'ikura',
    fr: 'combien (prix)',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いくらですか？', romaji: 'Ikura desu ka?', fr: 'Combien ça coûte ?' },
    ],
  },
  {
    kana: 'いま',
    romaji: 'ima',
    fr: 'maintenant',
    kanji: '今',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いま、なんじですか？', romaji: 'Ima, nanji desu ka?', fr: 'Maintenant, quelle heure est-il ?' },
    ],
  },
  {
    kana: 'いつ',
    romaji: 'itsu',
    fr: 'quand',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いつにほんにいきますか？', romaji: 'Itsu Nihon ni ikimasu ka?', fr: 'Quand allez-vous au Japon ?' },
    ],
  },
  {
    kana: 'きのう',
    romaji: 'kinō',
    fr: 'hier',
    kanji: '昨日',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'きのう、さしみをたべました。', romaji: 'Kinō, sashimi o tabemashita.', fr: 'Hier, j\'ai mangé du sashimi.' },
    ],
  },
  {
    kana: 'きょう',
    romaji: 'kyō',
    fr: 'aujourd\'hui',
    kanji: '今日',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'きょうはいいてんきですね。', romaji: 'Kyō wa ii tenki desu ne.', fr: 'Il fait beau aujourd\'hui, n\'est-ce pas ?' },
    ],
  },
  {
    kana: 'まだ',
    romaji: 'mada',
    fr: 'encore, toujours / pas encore',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'まだたべています。', romaji: 'Mada tabete imasu.', fr: 'Je mange encore.' },
      { jp: 'まだわかりません。', romaji: 'Mada wakarimasen.', fr: 'Je ne comprends pas encore.' },
    ],
  },
  {
    kana: 'また',
    romaji: 'mata',
    fr: 'encore, à nouveau',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'またにほんにきます！', romaji: 'Mata Nihon ni kimasu!', fr: 'Je reviendrai au Japon !' },
      { jp: 'またあいましょう。', romaji: 'Mata aimasho.', fr: 'Revoyons-nous.' },
    ],
  },
  {
    kana: 'も',
    romaji: 'mo',
    fr: 'aussi, également',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'わたしもいきます。', romaji: 'Watashi mo ikimasu.', fr: 'Moi aussi j\'y vais.' },
      { jp: 'さけもすきです。', romaji: 'Sake mo suki desu.', fr: 'J\'aime aussi le saké.' },
    ],
  },
  {
    kana: 'もっと',
    romaji: 'motto',
    fr: 'davantage, plus',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'みずをもっとください。', romaji: 'Mizu o motto kudasai.', fr: 'Donnez-moi plus d\'eau, s\'il vous plaît.' },
      { jp: 'もっとゆっくりはなしてください。', romaji: 'Motto yukkuri hanashite kudasai.', fr: 'Parlez plus lentement, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'なか',
    romaji: 'naka',
    fr: 'à l\'intérieur, au milieu',
    kanji: '中',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'かばんのなかにあります。', romaji: 'Kaban no naka ni arimasu.', fr: 'C\'est dans le sac.' },
    ],
  },
  {
    kana: 'おそい',
    romaji: 'osoi',
    fr: 'tard, lent, en retard',
    kanji: '遅い',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'でんしゃがおそいです。', romaji: 'Densha ga osoi desu.', fr: 'Le train est en retard.' },
    ],
  },
  {
    kana: 'おおきい',
    romaji: 'ōkii',
    fr: 'grand',
    kanji: '大きい',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'とうきょうはおおきいまちです。', romaji: 'Tōkyō wa ōkii machi desu.', fr: 'Tokyo est une grande ville.' },
    ],
  },
  {
    kana: 'さむい',
    romaji: 'samui',
    fr: 'froid (météo)',
    kanji: '寒い',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'きょうはさむいですね。', romaji: 'Kyō wa samui desu ne.', fr: 'Il fait froid aujourd\'hui, n\'est-ce pas ?' },
    ],
  },
  {
    kana: 'そうです',
    romaji: 'sō desu',
    fr: 'oui, c\'est ça, en effet',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'そうです！にほんがすきです。', romaji: 'Sō desu! Nihon ga suki desu.', fr: 'Oui, c\'est ça ! J\'aime le Japon.' },
    ],
  },
  {
    kana: 'それから',
    romaji: 'sorekara',
    fr: 'ensuite, et puis',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'すしをたべました。それからさけをのみました。', romaji: 'Sushi o tabemashita. Sorekara sake o nomimashita.', fr: 'J\'ai mangé des sushis. Ensuite j\'ai bu du saké.' },
    ],
  },
  {
    kana: 'たくさん',
    romaji: 'takusan',
    fr: 'beaucoup',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'たくさんたべました！', romaji: 'Takusan tabemashita!', fr: 'J\'ai beaucoup mangé !' },
      { jp: 'にほんにともだちがたくさんいます。', romaji: 'Nihon ni tomodachi ga takusan imasu.', fr: 'J\'ai beaucoup d\'amis au Japon.' },
    ],
  },
  {
    kana: 'とても',
    romaji: 'totemo',
    fr: 'très, vraiment',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'とてもたのしかったです！', romaji: 'Totemo tanoshikatta desu!', fr: 'C\'était vraiment agréable !' },
    ],
  },
  {
    kana: 'つめたい',
    romaji: 'tsumetai',
    fr: 'froid (au toucher, émotions)',
    kanji: '',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'つめたいみずをください。', romaji: 'Tsumetai mizu o kudasai.', fr: 'Donnez-moi de l\'eau froide, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'よく',
    romaji: 'yoku',
    fr: 'bien, souvent',
    kanji: '',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'よくにほんにきます。', romaji: 'Yoku Nihon ni kimasu.', fr: 'Je viens souvent au Japon.' },
    ],
  },
  {
    kana: 'ぜんぜん',
    romaji: 'zenzen',
    fr: 'pas du tout (avec négation) / totalement',
    kanji: '全然',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ぜんぜんわかりません。', romaji: 'Zenzen wakarimasen.', fr: 'Je ne comprends pas du tout.' },
      { jp: 'ぜんぜんだいじょうぶです！', romaji: 'Zenzen daijōbu desu!', fr: 'C\'est totalement sans problème !' },
    ],
  },

  // ── NOMS (Assimil)
  {
    kana: 'あさ',
    romaji: 'asa',
    fr: 'matin',
    kanji: '朝',
    theme: 'temps',
    theme_label: 'Temps',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'あさ、こうひーをのみます。', romaji: 'Asa, kōhī o nomimasu.', fr: 'Le matin, je bois un café.' },
    ],
  },
  {
    kana: 'でんわ',
    romaji: 'denwa',
    fr: 'téléphone',
    kanji: '電話',
    theme: 'quotidien',
    theme_label: 'Quotidien',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'でんわをかけてもいいですか？', romaji: 'Denwa o kakete mo ii desu ka?', fr: 'Puis-je téléphoner ?' },
    ],
  },
  {
    kana: 'デパート',
    romaji: 'depāto',
    fr: 'grand magasin',
    kanji: '',
    theme: 'lieux',
    theme_label: 'Lieux',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'デパートでかいものをします。', romaji: 'Depāto de kaimono o shimasu.', fr: 'Je fais des courses au grand magasin.' },
    ],
  },
  {
    kana: 'えいが',
    romaji: 'eiga',
    fr: 'film, cinéma',
    kanji: '映画',
    theme: 'loisirs',
    theme_label: 'Loisirs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんのえいがをみます。', romaji: 'Nihon no eiga o mimasu.', fr: 'Je regarde des films japonais.' },
    ],
  },
  {
    kana: 'えき',
    romaji: 'eki',
    fr: 'gare',
    kanji: '駅',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'つぎのえきはどこですか？', romaji: 'Tsugi no eki wa doko desu ka?', fr: 'Où est la prochaine gare ?' },
    ],
  },
  {
    kana: 'いえ',
    romaji: 'ie',
    fr: 'maison, foyer',
    kanji: '家',
    theme: 'lieux',
    theme_label: 'Lieux',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いえにかえります。', romaji: 'Ie ni kaerimasu.', fr: 'Je rentre à la maison.' },
    ],
  },
  {
    kana: 'じかん',
    romaji: 'jikan',
    fr: 'temps, heure (durée)',
    kanji: '時間',
    theme: 'temps',
    theme_label: 'Temps',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どのくらいじかんがかかりますか？', romaji: 'Dono kurai jikan ga kakarimasu ka?', fr: 'Combien de temps faut-il ?' },
    ],
  },
  {
    kana: 'きっさてん',
    romaji: 'kissaten',
    fr: 'salon de thé, café',
    kanji: '喫茶店',
    theme: 'lieux',
    theme_label: 'Lieux',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'きっさてんでこうひーをのみましょう。', romaji: 'Kissaten de kōhī o nomimasho.', fr: 'Allons boire un café dans un salon de thé.' },
    ],
  },
  {
    kana: 'こども',
    romaji: 'kodomo',
    fr: 'enfant',
    kanji: '子供',
    theme: 'famille',
    theme_label: 'Famille',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'こどもがふたりいます。', romaji: 'Kodomo ga futari imasu.', fr: 'J\'ai deux enfants.' },
    ],
  },
  {
    kana: 'にく',
    romaji: 'niku',
    fr: 'viande',
    kanji: '肉',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'わぎゅうのにくはさいこうです！', romaji: 'Wagyū no niku wa saikō desu!', fr: 'Le bœuf wagyu est le meilleur !' },
    ],
  },
  {
    kana: 'りょうり',
    romaji: 'ryōri',
    fr: 'cuisine, plat',
    kanji: '料理',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'このりょうりはなんですか？', romaji: 'Kono ryōri wa nan desu ka?', fr: 'Qu\'est-ce que c\'est comme plat ?' },
      { jp: 'にほんりょうりがだいすきです。', romaji: 'Nihon ryōri ga daisuki desu.', fr: 'J\'adore la cuisine japonaise.' },
    ],
  },
  {
    kana: 'てんき',
    romaji: 'tenki',
    fr: 'temps (météo)',
    kanji: '天気',
    theme: 'meteo',
    theme_label: 'Météo',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'てんきがいいですね。', romaji: 'Tenki ga ii desu ne.', fr: 'Il fait beau, n\'est-ce pas ?' },
      { jp: 'あしたのてんきはどうですか？', romaji: 'Ashita no tenki wa dō desu ka?', fr: 'Quel temps fera-t-il demain ?' },
    ],
  },
  {
    kana: 'ともだち',
    romaji: 'tomodachi',
    fr: 'ami',
    kanji: '友達',
    theme: 'famille',
    theme_label: 'Famille',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんじんのともだちとさけをのみました。', romaji: 'Nihonjin no tomodachi to sake o nomimashita.', fr: 'J\'ai bu du saké avec un ami japonais.' },
    ],
  },
  {
    kana: 'よる',
    romaji: 'yoru',
    fr: 'soir, nuit',
    kanji: '夜',
    theme: 'temps',
    theme_label: 'Temps',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'よるはしずかです。', romaji: 'Yoru wa shizuka desu.', fr: 'La nuit est calme.' },
    ],
  },

  // ── ADJECTIFS (Assimil)
  {
    kana: 'べんり',
    romaji: 'benri',
    fr: 'pratique, commode',
    kanji: '便利',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんのこうつうはとてもべんりです。', romaji: 'Nihon no kōtsū wa totemo benri desu.', fr: 'Les transports japonais sont très pratiques.' },
    ],
  },
  {
    kana: 'ひだり',
    romaji: 'hidari',
    fr: 'gauche (direction)',
    kanji: '左',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ひだりにまがってください。', romaji: 'Hidari ni magatte kudasai.', fr: 'Tournez à gauche, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'かんたん',
    romaji: 'kantan',
    fr: 'simple, facile',
    kanji: '簡単',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんごはかんたんじゃないです。', romaji: 'Nihongo wa kantan ja nai desu.', fr: 'Le japonais n\'est pas simple.' },
    ],
  },
  {
    kana: 'みぎ',
    romaji: 'migi',
    fr: 'droite (direction)',
    kanji: '右',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'みぎにまがってください。', romaji: 'Migi ni magatte kudasai.', fr: 'Tournez à droite, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'おいしい',
    romaji: 'oishii',
    fr: 'bon, délicieux',
    kanji: '',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'このさしみはとてもおいしいです！', romaji: 'Kono sashimi wa totemo oishii desu!', fr: 'Ce sashimi est vraiment délicieux !' },
    ],
  },
  {
    kana: 'たかい',
    romaji: 'takai',
    fr: 'cher, haut',
    kanji: '高い',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'このさけはたかいですね。', romaji: 'Kono sake wa takai desu ne.', fr: 'Ce saké est cher, n\'est-ce pas ?' },
    ],
  },
  {
    kana: 'うつくしい',
    romaji: 'utsukushii',
    fr: 'beau, magnifique',
    kanji: '美しい',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'さくらはうつくしいですね。', romaji: 'Sakura wa utsukushii desu ne.', fr: 'Les cerisiers sont magnifiques, n\'est-ce pas ?' },
    ],
  },

  // ── PRONOMS / EXPRESSIONS (Assimil)
  {
    kana: 'だれ',
    romaji: 'dare',
    fr: 'qui',
    kanji: '誰',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'だれですか？', romaji: 'Dare desu ka?', fr: 'Qui est-ce ?' },
    ],
  },
  {
    kana: 'なに',
    romaji: 'nani / nan',
    fr: 'quoi, quel',
    kanji: '何',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'これはなんですか？', romaji: 'Kore wa nan desu ka?', fr: 'Qu\'est-ce que c\'est ?' },
      { jp: 'なにをたべましょうか？', romaji: 'Nani o tabemasho ka?', fr: 'Qu\'allons-nous manger ?' },
    ],
  },
  {
    kana: 'わたし',
    romaji: 'watashi',
    fr: 'je, moi',
    kanji: '私',
    theme: 'mots_outils',
    theme_label: 'Mots-outils',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'わたしはフランスからきました。', romaji: 'Watashi wa Furansu kara kimashita.', fr: 'Je viens de France.' },
    ],
  },
  {
    kana: 'ちょっとまってください',
    romaji: 'chotto matte kudasai',
    fr: 'attendez un instant, s\'il vous plaît',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 2,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'ちょっとまってください。しゃしんをとります。', romaji: 'Chotto matte kudasai. Shashin o torimasu.', fr: 'Attendez un instant. Je prends une photo.' },
    ],
  },
  {
    kana: 'だいすきです',
    romaji: 'daisuki desu',
    fr: 'j\'adore, j\'aime beaucoup',
    kanji: '大好きです',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんのさけがだいすきです。', romaji: 'Nihon no sake ga daisuki desu.', fr: 'J\'adore le saké japonais.' },
    ],
  },
  {
    kana: 'どうも',
    romaji: 'dōmo',
    fr: 'merci beaucoup (familier)',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どうもありがとうございます。', romaji: 'Dōmo arigatō gozaimasu.', fr: 'Merci infiniment.' },
    ],
  },
  {
    kana: 'どうぞ',
    romaji: 'dōzo',
    fr: 'voici, je vous prie (on offre)',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どうぞ、すわってください。', romaji: 'Dōzo, suwatte kudasai.', fr: 'Asseyez-vous, je vous en prie.' },
    ],
  },
  {
    kana: 'いらっしゃいませ',
    romaji: 'irasshaimase',
    fr: 'bienvenue (dans un commerce)',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いらっしゃいませ！なんめいさまですか？', romaji: 'Irasshaimase! Nanmei-sama desu ka?', fr: 'Bienvenue ! Vous êtes combien ?' },
    ],
  },
  {
    kana: 'ください',
    romaji: 'kudasai',
    fr: 'donnez-moi, s\'il vous plaît',
    kanji: '下さい',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'みずをください。', romaji: 'Mizu o kudasai.', fr: 'De l\'eau, s\'il vous plaît.' },
      { jp: 'もうすこしじかんをください。', romaji: 'Mō sukoshi jikan o kudasai.', fr: 'Donnez-moi encore un peu de temps.' },
    ],
  },
  {
    kana: 'またね',
    romaji: 'matane',
    fr: 'à plus tard ! (familier)',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'じゃあ、またね！', romaji: 'Jā, matane!', fr: 'Hé bien, à plus tard !' },
    ],
  },
  {
    kana: 'じつは',
    romaji: 'jitsu wa',
    fr: 'en fait, à vrai dire',
    kanji: '実は',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 2,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'じつは、さけがだいすきです。', romaji: 'Jitsu wa, sake ga daisuki desu.', fr: 'En fait, j\'adore le saké.' },
    ],
  },
  {
    kana: 'ぜひ',
    romaji: 'zehi',
    fr: 'absolument, avec grand plaisir',
    kanji: '是非',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'にほんにまたきてください。—はい、ぜひ！', romaji: 'Nihon ni mata kite kudasai. — Hai, zehi!', fr: 'Revenez au Japon. — Oui, avec grand plaisir !' },
    ],
  },
  {
    kana: 'しています',
    romaji: 'shite imasu / mite imasu',
    fr: 'je suis en train de (forme progressive)',
    kanji: '',
    theme: 'grammaire',
    theme_label: 'Grammaire',
    level: 2,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'いま、てれびをみています。', romaji: 'Ima, terebi o mite imasu.', fr: 'En ce moment, je regarde la télé.' },
      { jp: 'にほんごをべんきょうしています。', romaji: 'Nihongo o benkyō shite imasu.', fr: 'Je suis en train d\'étudier le japonais.' },
    ],
  },
  {
    kana: 'すんでいます',
    romaji: 'sunde imasu',
    fr: 'j\'habite (forme progressive-continue)',
    kanji: '住んでいます',
    theme: 'grammaire',
    theme_label: 'Grammaire',
    level: 2,
    pack: 'perso',
    source: 'assimil',
    source_label: 'Assimil perso',
    examples: [
      { jp: 'どこにすんでいますか？', romaji: 'Doko ni sunde imasu ka?', fr: 'Où habitez-vous ?' },
      { jp: 'フランスにすんでいます。', romaji: 'Furansu ni sunde imasu.', fr: 'J\'habite en France.' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  //  SOURCE : BOUFFE — Vocabulaire gastronomique
  // ══════════════════════════════════════════════════════════════

  // ── VIANDES & POISSONS
  {
    kana: 'ぎゅうにく',
    romaji: 'gyūniku',
    fr: 'bœuf',
    kanji: '牛肉',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'わぎゅうのぎゅうにくはとてもおいしいです。', romaji: 'Wagyū no gyūniku wa totemo oishii desu.', fr: 'Le bœuf wagyu est très délicieux.' },
    ],
  },
  {
    kana: 'ぶたにく',
    romaji: 'butaniku',
    fr: 'porc',
    kanji: '豚肉',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'とんかつはぶたにくのりょうりです。', romaji: 'Tonkatsu wa butaniku no ryōri desu.', fr: 'Le tonkatsu est un plat de porc.' },
    ],
  },
  {
    kana: 'とりにく',
    romaji: 'toriniku',
    fr: 'poulet',
    kanji: '鶏肉',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'やきとりはとりにくをやいたものです。', romaji: 'Yakitori wa toriniku o yaita mono desu.', fr: 'Le yakitori c\'est du poulet grillé.' },
    ],
  },
  {
    kana: 'さかな',
    romaji: 'sakana',
    fr: 'poisson',
    kanji: '魚',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'にほんのさかなはとてもおいしい！', romaji: 'Nihon no sakana wa totemo oishii!', fr: 'Le poisson au Japon est vraiment délicieux !' },
    ],
  },
  {
    kana: 'えび',
    romaji: 'ebi',
    fr: 'crevette',
    kanji: '海老',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'えびのてんぷらがすきです。', romaji: 'Ebi no tempura ga suki desu.', fr: 'J\'aime la tempura de crevettes.' },
    ],
  },
  {
    kana: 'かに',
    romaji: 'kani',
    fr: 'crabe',
    kanji: '蟹',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'ほたて',
    romaji: 'hotate',
    fr: 'coquille Saint-Jacques',
    kanji: '帆立',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'かき',
    romaji: 'kaki',
    fr: 'huître',
    kanji: '牡蠣',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'いか',
    romaji: 'ika',
    fr: 'calamar',
    kanji: '烏賊',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'たこ',
    romaji: 'tako',
    fr: 'poulpe',
    kanji: '蛸',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'たこやきにはたこがはいっています。', romaji: 'Takoyaki ni wa tako ga haitte imasu.', fr: 'Le takoyaki contient du poulpe.' },
    ],
  },
  {
    kana: 'さば',
    romaji: 'saba',
    fr: 'maquereau',
    kanji: '鯖',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'たい',
    romaji: 'tai',
    fr: 'daurade',
    kanji: '鯛',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'ふぐ',
    romaji: 'fugu',
    fr: 'poisson-globe (met rare et dangereux)',
    kanji: '河豚',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'ふぐはたかいですが、おいしいです。', romaji: 'Fugu wa takai desu ga, oishii desu.', fr: 'Le fugu est cher mais délicieux.' },
    ],
  },

  // ── INGRÉDIENTS DE BASE
  {
    kana: 'やさい',
    romaji: 'yasai',
    fr: 'légumes',
    kanji: '野菜',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'こめ',
    romaji: 'kome',
    fr: 'riz (grain brut)',
    kanji: '米',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'めん',
    romaji: 'men',
    fr: 'nouilles',
    kanji: '麺',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'たまご',
    romaji: 'tamago',
    fr: 'œuf',
    kanji: '卵',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'とうふ',
    romaji: 'tōfu',
    fr: 'tofu',
    kanji: '豆腐',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'みそしるにはとうふがはいっています。', romaji: 'Misoshiru ni wa tōfu ga haitte imasu.', fr: 'La soupe miso contient du tofu.' },
    ],
  },
  {
    kana: 'みそ',
    romaji: 'miso',
    fr: 'pâte de soja fermentée',
    kanji: '味噌',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'まいあさみそしるをのみます。', romaji: 'Maiasa misoshiru o nomimasu.', fr: 'Je bois une soupe miso chaque matin.' },
    ],
  },
  {
    kana: 'しょうゆ',
    romaji: 'shōyu',
    fr: 'sauce soja',
    kanji: '醤油',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'しょうゆをかけますか？', romaji: 'Shōyu o kakemasu ka?', fr: 'Vous mettez de la sauce soja ?' },
    ],
  },
  {
    kana: 'しお',
    romaji: 'shio',
    fr: 'sel',
    kanji: '塩',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'だし',
    romaji: 'dashi',
    fr: 'bouillon japonais (base de cuisine)',
    kanji: '',
    theme: 'nourriture',
    theme_label: 'Nourriture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'だしはにほんりょうりのきほんです。', romaji: 'Dashi wa Nihon ryōri no kihon desu.', fr: 'Le dashi est la base de la cuisine japonaise.' },
    ],
  },

  // ── BOISSONS
  {
    kana: 'さけ',
    romaji: 'sake',
    fr: 'alcool, saké (générique)',
    kanji: '酒',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'さけがだいすきです！', romaji: 'Sake ga daisuki desu!', fr: 'J\'adore le saké !' },
    ],
  },
  {
    kana: 'にほんしゅ',
    romaji: 'nihonshu',
    fr: 'saké japonais (vin de riz)',
    kanji: '日本酒',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'にほんしゅをかんで、おねがいします。', romaji: 'Nihonshu o kande, onegai shimasu.', fr: 'Du saké chaud, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'しょうちゅう',
    romaji: 'shōchū',
    fr: 'alcool distillé japonais',
    kanji: '焼酎',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'うめしゅ',
    romaji: 'umeshu',
    fr: 'liqueur de prune',
    kanji: '梅酒',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'うめしゅはあまくておいしい！', romaji: 'Umeshu wa amakute oishii!', fr: 'La liqueur de prune est douce et délicieuse !' },
    ],
  },
  {
    kana: 'びーる',
    romaji: 'bīru',
    fr: 'bière',
    kanji: 'ビール',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'つめたいびーるをください！', romaji: 'Tsumetai bīru o kudasai!', fr: 'Une bière fraîche, s\'il vous plaît !' },
    ],
  },
  {
    kana: 'おちゃ',
    romaji: 'ocha',
    fr: 'thé (vert japonais)',
    kanji: 'お茶',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'おちゃをいっぱいどうぞ。', romaji: 'Ocha o ippai dōzo.', fr: 'Voici une tasse de thé.' },
    ],
  },
  {
    kana: 'みず',
    romaji: 'mizu',
    fr: 'eau',
    kanji: '水',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'おみずをください。', romaji: 'Omizu o kudasai.', fr: 'De l\'eau, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'こうひー',
    romaji: 'kōhī',
    fr: 'café',
    kanji: 'コーヒー',
    theme: 'boissons',
    theme_label: 'Boissons',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'こうひーをいっぱいおねがいします。', romaji: 'Kōhī o ippai onegaishimasu.', fr: 'Un café, s\'il vous plaît.' },
    ],
  },

  // ── PLATS JAPONAIS
  {
    kana: 'すし',
    romaji: 'sushi',
    fr: 'sushi',
    kanji: '寿司',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'すしをたべにいきましょう！', romaji: 'Sushi o tabe ni ikimasho!', fr: 'Allons manger des sushis !' },
    ],
  },
  {
    kana: 'さしみ',
    romaji: 'sashimi',
    fr: 'poisson cru tranché',
    kanji: '刺身',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'このさしみはとてもしんせんです。', romaji: 'Kono sashimi wa totemo shinsen desu.', fr: 'Ce sashimi est très frais.' },
    ],
  },
  {
    kana: 'てんぷら',
    romaji: 'tempura',
    fr: 'beignets frits (légumes, crevettes)',
    kanji: '天ぷら',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'やきとり',
    romaji: 'yakitori',
    fr: 'brochettes de poulet grillé',
    kanji: '焼き鳥',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'やきとりをよんほんください。', romaji: 'Yakitori o yonhon kudasai.', fr: 'Quatre brochettes de yakitori, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'たこやき',
    romaji: 'takoyaki',
    fr: 'boulettes de poulpe',
    kanji: 'たこ焼き',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'おこのみやき',
    romaji: 'okonomiyaki',
    fr: 'crêpe japonaise garnie',
    kanji: 'お好み焼き',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'うどん',
    romaji: 'udon',
    fr: 'nouilles épaisses',
    kanji: 'うどん',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'そば',
    romaji: 'soba',
    fr: 'nouilles de sarrasin',
    kanji: 'そば',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'ざるそばをひとつおねがいします。', romaji: 'Zaru soba o hitotsu onegai shimasu.', fr: 'Un zaru soba, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'らーめん',
    romaji: 'rāmen',
    fr: 'soupe de nouilles chinoises',
    kanji: 'ラーメン',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'とんこつらーめんがだいすきです！', romaji: 'Tonkotsu rāmen ga daisuki desu!', fr: 'J\'adore le ramen tonkotsu !' },
    ],
  },
  {
    kana: 'ぎょうざ',
    romaji: 'gyōza',
    fr: 'raviolis japonais',
    kanji: '餃子',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'おにぎり',
    romaji: 'onigiri',
    fr: 'boule de riz',
    kanji: 'おにぎり',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'コンビニのおにぎりがおいしいです。', romaji: 'Konbini no onigiri ga oishii desu.', fr: 'Les onigiri du konbini sont délicieux.' },
    ],
  },
  {
    kana: 'べんとう',
    romaji: 'bentō',
    fr: 'boîte-repas',
    kanji: '弁当',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'えきべんとうをかいました。', romaji: 'Ekibentō o kaimashita.', fr: 'J\'ai acheté un bento de gare.' },
    ],
  },
  {
    kana: 'ていしょく',
    romaji: 'teishoku',
    fr: 'menu fixe (riz + soupe + plat)',
    kanji: '定食',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'ていしょくをひとつおねがいします。', romaji: 'Teishoku o hitotsu onegai shimasu.', fr: 'Un menu fixe, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'かいせき',
    romaji: 'kaiseki',
    fr: 'haute cuisine japonaise (multi-services)',
    kanji: '懐石',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'りょかんでかいせきりょうりをたべました。', romaji: 'Ryokan de kaiseki ryōri o tabemashita.', fr: 'J\'ai mangé un repas kaiseki au ryokan.' },
    ],
  },
  {
    kana: 'なべもの',
    romaji: 'nabemono',
    fr: 'plat mijoté japonais (fondue)',
    kanji: '鍋物',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'やきにく',
    romaji: 'yakiniku',
    fr: 'barbecue japonais',
    kanji: '焼肉',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'やきにくをたべにいきましょう！', romaji: 'Yakiniku o tabe ni ikimasho!', fr: 'Allons manger du yakiniku !' },
    ],
  },
  {
    kana: 'しゃぶしゃぶ',
    romaji: 'shabu-shabu',
    fr: 'fondue japonaise (viande fine)',
    kanji: 'しゃぶしゃぶ',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'みそしる',
    romaji: 'misoshiru',
    fr: 'soupe miso',
    kanji: 'みそ汁',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'みそしるをまいにちのみます。', romaji: 'Misoshiru o mainichi nomimasu.', fr: 'Je bois de la soupe miso tous les jours.' },
    ],
  },
  {
    kana: 'からあげ',
    romaji: 'karaage',
    fr: 'poulet frit japonais',
    kanji: '唐揚げ',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'もち',
    romaji: 'mochi',
    fr: 'gâteau de riz gluant',
    kanji: '餅',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'もちはやわらかくておいしいです。', romaji: 'Mochi wa yawarakakute oishii desu.', fr: 'Le mochi est moelleux et délicieux.' },
    ],
  },
  {
    kana: 'なっとう',
    romaji: 'nattō',
    fr: 'haricots de soja fermentés',
    kanji: '納豆',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'なっとうはすきですか？ちょっとむずかしいです…', romaji: 'Nattō wa suki desu ka? Chotto muzukashii desu…', fr: 'Vous aimez le nattō ? C\'est un peu difficile…' },
    ],
  },
  {
    kana: 'わぎゅう',
    romaji: 'wagyū',
    fr: 'bœuf japonais (wagyu)',
    kanji: '和牛',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'わぎゅうはせかいいちのぎゅうにくです！', romaji: 'Wagyū wa sekai ichi no gyūniku desu!', fr: 'Le wagyu est le meilleur bœuf du monde !' },
    ],
  },
  {
    kana: 'おつまみ',
    romaji: 'otsumami',
    fr: 'amuse-bouche (avec une boisson)',
    kanji: 'おつまみ',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'おつまみをおねがいします。', romaji: 'Otsumami o onegai shimasu.', fr: 'Des amuse-bouches, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'うめぼし',
    romaji: 'umeboshi',
    fr: 'prune salée et séchée',
    kanji: '梅干し',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'えだまめ',
    romaji: 'edamame',
    fr: 'fèves de soja',
    kanji: '枝豆',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'えだまめとびーるはさいこうのくみあわせです！', romaji: 'Edamame to bīru wa saikō no kumiawase desu!', fr: 'Edamame et bière, c\'est la combinaison parfaite !' },
    ],
  },
  {
    kana: 'つけもの',
    romaji: 'tsukemono',
    fr: 'légumes marinés',
    kanji: '漬物',
    theme: 'plats',
    theme_label: 'Plats japonais',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [],
  },
  {
    kana: 'さどう',
    romaji: 'sadō',
    fr: 'cérémonie du thé',
    kanji: '茶道',
    theme: 'culture',
    theme_label: 'Culture',
    level: 1,
    pack: 'perso',
    source: 'bouffe',
    source_label: 'Vocabulaire gastronomique',
    examples: [
      { jp: 'きょうとでさどうをたいけんしました。', romaji: 'Kyōto de sadō o taiken shimashita.', fr: 'J\'ai expérimenté la cérémonie du thé à Kyoto.' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  //  SOURCE : MICHELIN — Guide Michelin vocabulaire de base
  // ══════════════════════════════════════════════════════════════

  // ── BASE / PRÉSENTATIONS
  {
    kana: 'はい',
    romaji: 'hai',
    fr: 'oui',
    kanji: '',
    theme: 'base',
    theme_label: 'Base',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'はい、わかりました。', romaji: 'Hai, wakarimashita.', fr: 'Oui, j\'ai compris.' },
    ],
  },
  {
    kana: 'おげんきですか',
    romaji: 'ogenki desu ka',
    fr: 'comment allez-vous ?',
    kanji: 'お元気ですか',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'おげんきですか？—はい、おかげさまで。', romaji: 'Ogenki desu ka? — Hai, okage-sama de.', fr: 'Comment allez-vous ? — Bien, merci.' },
    ],
  },
  {
    kana: 'はじめまして',
    romaji: 'hajimemashite',
    fr: 'enchanté(e) (première rencontre)',
    kanji: '',
    theme: 'base',
    theme_label: 'Base',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'はじめまして。わたしはフランスからきました。', romaji: 'Hajimemashite. Watashi wa Furansu kara kimashita.', fr: 'Enchanté(e). Je viens de France.' },
    ],
  },
  {
    kana: 'おなまえはなんですか',
    romaji: 'o-namae wa nan desu ka',
    fr: 'quel est votre nom ?',
    kanji: 'お名前は何ですか',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'わたしは…です',
    romaji: 'watashi wa … desu',
    fr: 'je m\'appelle…',
    kanji: '私は…です',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'わたしはぷるーむです。', romaji: 'Watashi wa Purūmu desu.', fr: 'Je m\'appelle Plume.' },
    ],
  },
  {
    kana: 'わたしはフランスじんです',
    romaji: 'watashi wa Furansu-jin desu',
    fr: 'je suis français(e)',
    kanji: '私はフランス人です',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'わたしはフランスじんです。にほんがだいすきです。', romaji: 'Watashi wa Furansu-jin desu. Nihon ga daisuki desu.', fr: 'Je suis français(e). J\'adore le Japon.' },
    ],
  },
  {
    kana: 'もういちどいってください',
    romaji: 'mō ichido itte kudasai',
    fr: 'pouvez-vous répéter ?',
    kanji: 'もう一度言ってください',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'すみません、もういちどいってください。', romaji: 'Sumimasen, mō ichido itte kudasai.', fr: 'Excusez-moi, pouvez-vous répéter ?' },
    ],
  },
  {
    kana: 'えいごではなせますか',
    romaji: 'eigo ga hanasemasu ka',
    fr: 'parlez-vous anglais ?',
    kanji: '英語が話せますか',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'えいごではなせますか？にほんごがむずかしいです。', romaji: 'Eigo ga hanasemasu ka? Nihongo ga muzukashii desu.', fr: 'Parlez-vous anglais ? Le japonais est difficile.' },
    ],
  },
  {
    kana: '…がきらいです',
    romaji: '… ga kirai desu',
    fr: 'je n\'aime pas …',
    kanji: '…が嫌いです',
    theme: 'base',
    theme_label: 'Base',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'なっとうがきらいです。ごめんなさい！', romaji: 'Nattō ga kirai desu. Gomen nasai!', fr: 'Je n\'aime pas le nattō. Désolé !' },
    ],
  },

  // ── S'ORIENTER (Michelin)
  {
    kana: 'まっすぐ',
    romaji: 'massugu',
    fr: 'tout droit',
    kanji: '真っ直ぐ',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'まっすぐいってください。', romaji: 'Massugu itte kudasai.', fr: 'Allez tout droit, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'まえ',
    romaji: 'mae',
    fr: 'devant, avant',
    kanji: '前',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'えきのまえにあります。', romaji: 'Eki no mae ni arimasu.', fr: 'C\'est devant la gare.' },
    ],
  },
  {
    kana: 'うしろ',
    romaji: 'ushiro',
    fr: 'derrière',
    kanji: '後ろ',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: '…にいきたいです',
    romaji: '… ni ikitai desu',
    fr: 'je veux aller à …',
    kanji: '…に行きたいです',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'きんかくじにいきたいです。', romaji: 'Kinkakuji ni ikitai desu.', fr: 'Je veux aller au Kinkaku-ji.' },
      { jp: 'このさけのくらにいきたいです。', romaji: 'Kono sake no kura ni ikitai desu.', fr: 'Je veux aller à cette cave à saké.' },
    ],
  },
  {
    kana: '…はどこですか',
    romaji: '… wa doko desu ka',
    fr: 'où se trouve … ?',
    kanji: '',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'トイレはどこですか？', romaji: 'Toire wa doko desu ka?', fr: 'Où sont les toilettes ?' },
      { jp: 'さいきんのえきはどこですか？', romaji: 'Saikin no eki wa doko desu ka?', fr: 'Où est la gare la plus proche ?' },
    ],
  },
  {
    kana: 'まよいました',
    romaji: 'mayoimashita',
    fr: 'je suis perdu(e)',
    kanji: '迷いました',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'すみません、まよいました。たすけてください。', romaji: 'Sumimasen, mayoimashita. Tasukete kudasai.', fr: 'Excusez-moi, je suis perdu(e). Aidez-moi.' },
    ],
  },
  {
    kana: 'あるいていけますか',
    romaji: 'aruite ikemasu ka',
    fr: 'peut-on y aller à pied ?',
    kanji: '歩いて行けますか',
    theme: 'orientation',
    theme_label: 'Orientation',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },

  // ── ARGENT / ACHATS (Michelin)
  {
    kana: 'ぎんこう',
    romaji: 'ginkō',
    fr: 'banque',
    kanji: '銀行',
    theme: 'lieux',
    theme_label: 'Lieux',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'りょうがえができますか',
    romaji: 'ryōgae ga dekimasu ka',
    fr: 'pouvez-vous changer de l\'argent ?',
    kanji: '両替ができますか',
    theme: 'argent',
    theme_label: 'Argent',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'くれじっとかーどはつかえますか',
    romaji: 'kurejitto kādo wa tsukaemasu ka',
    fr: 'vous prenez les cartes de crédit ?',
    kanji: 'クレジットカードは使えますか',
    theme: 'argent',
    theme_label: 'Argent',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'くれじっとかーどはつかえますか？', romaji: 'Kurejitto kādo wa tsukaemasu ka?', fr: 'Acceptez-vous les cartes de crédit ?' },
    ],
  },
  {
    kana: 'たかい / やすい',
    romaji: 'takai / yasui',
    fr: 'cher / bon marché',
    kanji: '高い / 安い',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'このさけはやすいですが、おいしいです。', romaji: 'Kono sake wa yasui desu ga, oishii desu.', fr: 'Ce saké est bon marché mais délicieux.' },
    ],
  },
  {
    kana: 'おおきい / ちいさい',
    romaji: 'ōkii / chiisai',
    fr: 'grand / petit',
    kanji: '大きい / 小さい',
    theme: 'adjectifs',
    theme_label: 'Adjectifs',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'もっとおおきいサイズはありますか？', romaji: 'Motto ōkii saizu wa arimasu ka?', fr: 'Avez-vous une plus grande taille ?' },
    ],
  },
  {
    kana: 'これをください',
    romaji: 'kore o kudasai',
    fr: 'je prends ça',
    kanji: '',
    theme: 'expressions',
    theme_label: 'Expressions',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'これをください。いくらですか？', romaji: 'Kore o kudasai. Ikura desu ka?', fr: 'Je prends ça. Combien ça coûte ?' },
    ],
  },

  // ── HÔTEL (Michelin)
  {
    kana: 'へやをよやくしたいです',
    romaji: 'heya o yoyaku shitai desu',
    fr: 'je voudrais réserver une chambre',
    kanji: '部屋を予約したいです',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'よやくはしました',
    romaji: 'yoyaku wa shimashita',
    fr: 'j\'ai une réservation',
    kanji: '予約はしました',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'よやくはしました。なまえはぷるーむです。', romaji: 'Yoyaku wa shimashita. Namae wa Purūmu desu.', fr: 'J\'ai une réservation. Au nom de Plume.' },
    ],
  },
  {
    kana: 'わしつ / ようしつ',
    romaji: 'washitsu / yōshitsu',
    fr: 'chambre japonaise / occidentale',
    kanji: '和室 / 洋室',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'わしつをおねがいします。', romaji: 'Washitsu o onegai shimasu.', fr: 'Une chambre japonaise, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'いっぱくいくらですか',
    romaji: 'ippaku ikura desu ka',
    fr: 'quel est le prix de la nuit ?',
    kanji: '一泊いくらですか',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'にもつをあずけてもいいですか',
    romaji: 'nimotsu o azukete mo ii desu ka',
    fr: 'puis-je laisser mes bagages ?',
    kanji: '荷物を預けてもいいですか',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'かぎ',
    romaji: 'kagi',
    fr: 'clé',
    kanji: '鍵',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'かぎをわすれました！', romaji: 'Kagi o wasuremashita!', fr: 'J\'ai oublié ma clé !' },
    ],
  },
  {
    kana: 'たくしーをよんでください',
    romaji: 'takushī o yonde kudasai',
    fr: 'appelez-moi un taxi, s\'il vous plaît',
    kanji: 'タクシーを呼んでください',
    theme: 'hotel',
    theme_label: 'Hôtel',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },

  // ── RESTAURANT (Michelin)
  {
    kana: 'ふたりおねがいします',
    romaji: 'futari onegai shimasu',
    fr: 'une table pour deux, s\'il vous plaît',
    kanji: '二人お願いします',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'いらっしゃいませ！—ふたりおねがいします。', romaji: 'Irasshaimase! — Futari onegai shimasu.', fr: 'Bienvenue ! — Une table pour deux, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'えいごのめにゅーはありますか',
    romaji: 'eigo no menyū wa arimasu ka',
    fr: 'avez-vous un menu en anglais ?',
    kanji: '英語のメニューはありますか',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ちょうしょく / ちゅうしょく / ゆうしょく',
    romaji: 'chōshoku / chūshoku / yūshoku',
    fr: 'petit-déjeuner / déjeuner / dîner',
    kanji: '朝食 / 昼食 / 夕食',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'ゆうしょくはなんじからですか？', romaji: 'Yūshoku wa nanji kara desu ka?', fr: 'À quelle heure commence le dîner ?' },
    ],
  },
  {
    kana: 'おなかがすきました',
    romaji: 'onaka ga sukimashita',
    fr: 'j\'ai faim',
    kanji: 'お腹が空きました',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'おなかがすきました！はやくたべましょう。', romaji: 'Onaka ga sukimashita! Hayaku tabemasho.', fr: 'J\'ai faim ! Mangeons vite.' },
    ],
  },
  {
    kana: 'おなかがいっぱいです',
    romaji: 'onaka ga ippai desu',
    fr: 'je n\'ai plus faim, je suis repu(e)',
    kanji: 'お腹がいっぱいです',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'おなかがいっぱいです！でもまだたべられます。', romaji: 'Onaka ga ippai desu! Demo mada taberaremasu.', fr: 'Je suis repu(e) ! Mais je peux encore manger.' },
    ],
  },
  {
    kana: 'すみません、おかんじょうおねがいします',
    romaji: 'sumimasen, okanjō onegai shimasu',
    fr: 'l\'addition, s\'il vous plaît',
    kanji: 'すみません、お勘定お願いします',
    theme: 'restaurant',
    theme_label: 'Restaurant',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },

  // ── URGENCES / SANTÉ (Michelin)
  {
    kana: 'あたまがいたいです',
    romaji: 'atama ga itai desu',
    fr: 'j\'ai mal à la tête',
    kanji: '頭が痛いです',
    theme: 'sante',
    theme_label: 'Santé',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'おなかがいたいです',
    romaji: 'onaka ga itai desu',
    fr: 'j\'ai mal au ventre',
    kanji: 'お腹が痛いです',
    theme: 'sante',
    theme_label: 'Santé',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'たすけて！',
    romaji: 'tasukete!',
    fr: 'au secours !',
    kanji: '助けて！',
    theme: 'sante',
    theme_label: 'Santé',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'きゅうきゅうしゃをよんでください',
    romaji: 'kyūkyūsha o yonde kudasai',
    fr: 'appelez une ambulance',
    kanji: '救急車を呼んでください',
    theme: 'sante',
    theme_label: 'Santé',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'いしゃがひつようです',
    romaji: 'isha ga hitsuyō desu',
    fr: 'j\'ai besoin d\'un médecin',
    kanji: '医者が必要です',
    theme: 'sante',
    theme_label: 'Santé',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'こうばん / やっきょく',
    romaji: 'kōban / yakkyoku',
    fr: 'poste de police / pharmacie',
    kanji: '交番 / 薬局',
    theme: 'sante',
    theme_label: 'Santé',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'ちかくにやっきょくはありますか？', romaji: 'Chikaku ni yakkyoku wa arimasu ka?', fr: 'Y a-t-il une pharmacie à proximité ?' },
    ],
  },

  // ── TRANSPORTS (Michelin)
  {
    kana: 'ひこうき / くうこう',
    romaji: 'hikōki / kūkō',
    fr: 'avion / aéroport',
    kanji: '飛行機 / 空港',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'くうこうまでどのくらいかかりますか？', romaji: 'Kūkō made dono kurai kakarimasu ka?', fr: 'Combien de temps faut-il pour aller à l\'aéroport ?' },
    ],
  },
  {
    kana: 'ちかてつ',
    romaji: 'chikatetsu',
    fr: 'métro',
    kanji: '地下鉄',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'ちかてつはべんりです。', romaji: 'Chikatetsu wa benri desu.', fr: 'Le métro est pratique.' },
    ],
  },
  {
    kana: 'じてんしゃ',
    romaji: 'jitensha',
    fr: 'bicyclette',
    kanji: '自転車',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: '…ゆきのきっぷをください',
    romaji: '… yuki no kippu o kudasai',
    fr: 'un billet pour …, s\'il vous plaît',
    kanji: '…行きの切符をください',
    theme: 'transport',
    theme_label: 'Transport',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'きょうとゆきのきっぷをください。', romaji: 'Kyōto yuki no kippu o kudasai.', fr: 'Un billet pour Kyoto, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'かたみちきっぷ / おうふくきっぷ',
    romaji: 'katamichi kippu / ōfuku kippu',
    fr: 'aller simple / aller-retour',
    kanji: '片道切符 / 往復切符',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'おうふくきっぷをください。', romaji: 'Ōfuku kippu o kudasai.', fr: 'Un aller-retour, s\'il vous plaît.' },
    ],
  },
  {
    kana: 'していせき / じゆうせき',
    romaji: 'shitei seki / jiyū seki',
    fr: 'place réservée / non réservée',
    kanji: '指定席 / 自由席',
    theme: 'transport',
    theme_label: 'Transport',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'なんじにつきますか',
    romaji: 'nanji ni tsukimasu ka',
    fr: 'à quelle heure arrive-t-on ?',
    kanji: '何時に着きますか',
    theme: 'transport',
    theme_label: 'Transport',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ここでとまってください',
    romaji: 'koko de tomatte kudasai',
    fr: 'arrêtez-vous ici, s\'il vous plaît',
    kanji: 'ここで止まってください',
    theme: 'transport',
    theme_label: 'Transport',
    level: 2,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },

  // ── NOMBRES (Michelin)
  {
    kana: 'れい / ぜろ',
    romaji: 'rei / zero',
    fr: '0 (zéro)',
    kanji: '零',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'いち',
    romaji: 'ichi',
    fr: '1 (un)',
    kanji: '一',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'に',
    romaji: 'ni',
    fr: '2 (deux)',
    kanji: '二',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'さん',
    romaji: 'san',
    fr: '3 (trois)',
    kanji: '三',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'よん',
    romaji: 'yon',
    fr: '4 (quatre)',
    kanji: '四',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ご',
    romaji: 'go',
    fr: '5 (cinq)',
    kanji: '五',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ろく',
    romaji: 'roku',
    fr: '6 (six)',
    kanji: '六',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'なな',
    romaji: 'nana',
    fr: '7 (sept)',
    kanji: '七',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'はち',
    romaji: 'hachi',
    fr: '8 (huit)',
    kanji: '八',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'きゅう',
    romaji: 'kyū',
    fr: '9 (neuf)',
    kanji: '九',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'じゅう',
    romaji: 'jū',
    fr: '10 (dix)',
    kanji: '十',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ひゃく',
    romaji: 'hyaku',
    fr: '100 (cent)',
    kanji: '百',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'せん',
    romaji: 'sen',
    fr: '1 000 (mille)',
    kanji: '千',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'いっせんえんです。', romaji: 'Issen en desu.', fr: 'C\'est mille yens.' },
    ],
  },
  {
    kana: 'いちまん',
    romaji: 'ichiman',
    fr: '10 000 (dix mille)',
    kanji: '一万',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'いちまんえんのさけをかいました。', romaji: 'Ichiman en no sake o kaimashita.', fr: 'J\'ai acheté un saké à dix mille yens.' },
    ],
  },
  {
    kana: 'ひとり',
    romaji: 'hitori',
    fr: '1 personne',
    kanji: '一人',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },
  {
    kana: 'ふたり',
    romaji: 'futari',
    fr: '2 personnes',
    kanji: '二人',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [
      { jp: 'ふたりでたべにきました。', romaji: 'Futari de tabe ni kimashita.', fr: 'Nous sommes venus manger à deux.' },
    ],
  },
  {
    kana: 'さんにん',
    romaji: 'sannin',
    fr: '3 personnes',
    kanji: '三人',
    theme: 'nombres',
    theme_label: 'Nombres',
    level: 1,
    pack: 'perso',
    source: 'michelin',
    source_label: 'Guide Michelin',
    examples: [],
  },

];

// ── Métadonnées des thèmes du dico perso
const DICO_PERSO_META = {
  pack: 'perso',
  label: 'Perso',
  icon: '📖',
  sources: {
    assimil:  { label: 'Assimil perso',           icon: '📝', color: '#5a3a6b' },
    bouffe:   { label: 'Vocabulaire gastronomique', icon: '🍜', color: '#8a3a1a' },
    michelin: { label: 'Guide Michelin',           icon: '🔴', color: '#b5342a' },
  },
  themes: {
    verbes:      { label: 'Verbes',         icon: '⚡', color: '#5a4a1a' },
    mots_outils: { label: 'Mots-outils',    icon: '⟡', color: '#3d5a3d' },
    adjectifs:   { label: 'Adjectifs',      icon: '✎', color: '#3a5a3a' },
    orientation: { label: 'Orientation',    icon: '🧭', color: '#1e3a5f' },
    transport:   { label: 'Transport',      icon: '🚃', color: '#1e3a5f' },
    hotel:       { label: 'Hôtel',          icon: '🏯', color: '#2a7a6e' },
    restaurant:  { label: 'Restaurant',     icon: '🍜', color: '#b5342a' },
    nourriture:  { label: 'Nourriture',     icon: '🍱', color: '#8a3a1a' },
    boissons:    { label: 'Boissons',       icon: '🍶', color: '#2a5a7a' },
    plats:       { label: 'Plats japonais', icon: '🍣', color: '#7a2a1a' },
    sante:       { label: 'Santé',          icon: '🏥', color: '#7a2a2a' },
    lieux:       { label: 'Lieux',          icon: '📍', color: '#1a4a5a' },
    temps:       { label: 'Temps',          icon: '🕐', color: '#4a4a1a' },
    meteo:       { label: 'Météo',          icon: '🌤', color: '#2a5a7a' },
    famille:     { label: 'Famille',        icon: '👨‍👩‍👧', color: '#6b4a1a' },
    base:        { label: 'Base',           icon: '🙏', color: '#6b3a6b' },
    argent:      { label: 'Argent',         icon: '💴', color: '#3a5a1a' },
    nombres:     { label: 'Nombres',        icon: '🔢', color: '#2a4a6e' },
    expressions: { label: 'Expressions',    icon: '💬', color: '#5a1a5a' },
    grammaire:   { label: 'Grammaire',      icon: '📐', color: '#1a3a5a' },
    culture:     { label: 'Culture',        icon: '⛩', color: '#6b3a1a' },
    loisirs:     { label: 'Loisirs',        icon: '🎌', color: '#3a4a6b' },
    quotidien:   { label: 'Quotidien',      icon: '🌸', color: '#5a3a5a' },
  },
};

// Total : ~250 entrées — 3 sources : assimil, bouffe, michelin
